name: Gradle test (fast)

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
  pull_request:

permissions:
  checks: write
  contents: read

jobs:
  atlas:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'fast'
  atlas-video:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'video'
  atlas-controller-api:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'controller-api'
  atlas-controller-api-2:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'controller-api-2'
  atlas-humanoid-behaviors:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'humanoid-behaviors'
  atlas-humanoid-flat-ground:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'humanoid-flat-ground'
  atlas-humanoid-flat-ground-bullet:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'humanoid-flat-ground-bullet'
  atlas-humanoid-obstacle:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'humanoid-obstacle'
  atlas-humanoid-obstacle-2:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'humanoid-obstacle-2'
      requires-self-hosted: true
  atlas-humanoid-push-recovery:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'humanoid-push-recovery'
  atlas-humanoid-rough-terrain:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'humanoid-rough-terrain'
  atlas-humanoid-toolbox:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      extra-repos: '["ihmc-open-robotics-software"]'
      test-category: 'humanoid-toolbox'

  update-evergreen:
    name: Force update on evergreen
    runs-on: ubuntu-latest
    needs: 
      - atlas
      - atlas-video
      - atlas-controller-api
      - atlas-controller-api-2
      - atlas-humanoid-behaviors
      - atlas-humanoid-flat-ground
      - atlas-humanoid-flat-ground-bullet
      - atlas-humanoid-obstacle
      - atlas-humanoid-obstacle-2
      - atlas-humanoid-push-recovery
      - atlas-humanoid-rough-terrain
      - atlas-humanoid-toolbox
    if: always() # This ensures the job runs even if one of the dependent jobs fails
    steps:
      - name: Call API with curl
        uses: ihmcrobotics/ihmc-actions/.github/actions/force-update-evergreen@main
